---
# Secret for additional scrape configs
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: serversage
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'external-application'
      static_configs:
        - targets: ['192.168.1.10:8080']
          labels:
            env: 'external-datacenter'
            service: 'myapp'
---